version: '3.5'

services:
  postgres:
    container_name: koperasi_postgres
    image: postgres
    environment:
      POSTGRES_USER: koperasi
      POSTGRES_PASSWORD: koperasi
      POSTGRES_DB: koperasi
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./sql/koperasi.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: